### ISSUE TITLE
This Repo

### ISSUE THREAD

**Issue by Maikuolan** [ircmaxell/password_compat#97]
Hi,

I'm just wondering whether this repo is still being actively maintained by its owner? I'd been recently considering trying to implement something like what this package is intended to do, and it seems like package could be quite useful, but I can see four open pull requests to this repo currently, the oldest open since 2013 and the newest since 2015, and a number of forks with commits made since after the last commit to the parent; Not sure whether it would be better to work directly from the parent, from one of the forks, or something else.

Your input appreciated, and cheers. :-)

**Comment by miquelfire** [comment]
This library is a polyfill for PHP versions below 5.5. If you're using PHP 5.5 or higher (or only supporting that version or higher), then you don't even need this library.

**Comment by Maikuolan** [comment]
Hi miquelfire,

Yes, I understand what this repo is for, and that's why I've been considering using it. ;-)

I have some packages which are intended for PHP > 5.5.0, and one of my users is using PHP 5.4.45, so I've been considering building a compatibility bridge for these packages, for this user and others like this user.

My question is whether this repo is being actively maintained, and whether it would be better to use the parent repo or one of its forks, due to that there seems to be open pull requests which are over a year old now.

**Comment by StudioJunkyard** [comment]
Try contacting the author of this repo on Reddit, he seems to be more active there.

**Comment by Maikuolan** [comment]
Cheers; I'll give that a try. :-)

I'll leave the issue open for now; If I'm able to get in touch with him, I'll comment his response here and close the issue.

**Comment by GrahamCampbell** [comment]
Yes, this maintained, It just already works fine, so needs no changes. :)

**Comment by ircmaxell** [comment]
Yes, it is still maintained. To date there have been no issues that in my opinion warranted a release (since this project is mirrored in many downstream repositories such as RHEL.

Additionally, it is in "maintenance mode", which means all active development has stopped, and only significant bug fixes or security vulnerabilities will be fixed. This is due to the target compatibility modes and the versions that this targets. 5.4 is EOL (as is 5.5), so therefore nobody should be using them for new projects. Hence the lack of activity here (its a simple and stable lib).

**Comment by Maikuolan** [comment]
Cheers for the response; That clears it all up. :-)
